Created meme generator app with basic functionality
GKiant/18-meme-generator pull request #2
Opened 2023-03-05 12:16 UTC by GKiant

2023-03-05 12:29 UTC, GKiant commented
Approve my request pls

2023-03-05 12:38 UTC, SaintNekit requested changes

2023-03-05 12:38 UTC, SaintNekit commented on src/App.jsx
> +import React from "react";
unnecessary import in react version > 17

2023-03-05 12:38 UTC, SaintNekit commented on src/components/Header.jsx
> +import React from "react";
unnecessary import in react version > 17

2023-03-05 12:38 UTC, SaintNekit commented on src/components/Meme.jsx
> +  const [allMemes, setAllMemes] = useState([]);
why use state used differently? it's just const [] = useState()

2023-03-05 12:38 UTC, SaintNekit commented on src/components/Meme.jsx
> +      setAllMemes(data.data.memes);
you could use try/catch block for async functions or then operator, it could be const data = await fetch(url).then(res => res.json)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

2023-03-05 12:38 UTC, SaintNekit commented on src/components/Meme.jsx
> +  function getMemeImage() {
why not arrow functions?

2023-03-05 12:38 UTC, SaintNekit commented on src/index.css
> +  color: white;
use rgba or hex colors

2023-03-09 15:46 UTC, SaintNekit approved these changes

2023-03-09 15:46 UTC, SaintNekit commented on src/components/Meme.jsx
> +  function handleChange(event) {
some functions arrow, some simple functions - I prefer singleton approach in development (regular function or arrow functions everywhere)

2023-03-10 21:27 UTC, merged